version: '3'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3006:3306"
    volumes:
      - ./Seed:/docker-entrypoint-initdb.d

  php:
    build: .
    restart: always
    volumes:
      - ./Application:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db


